apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: ClusterIP
  ports:
    -
      targetPort: 8080
      port: 8080
      noderPort: 30080
  selectors:
    name: simple-webapp
