apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaSet
  labels:
    app: my-app
    type: front-end
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: my-app
        type: front-end
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 3
  selectors:
    matchLables:
      app: my-app
