apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: demo-voting-app
spec:
  template:
    metadata:
      name: postgres-deployment
      labels:
        app: demo-voting-app
        name: postgres-deployment
    spec:
      containers:
        - name: postgres
          image: postgres:9.4
      env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: demo-voting-app
      name: postgres-deployment
