apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app-deployment
  labels:
    app: demo-voting-app
spec:
  template:
    metadata:
      name: result-app-deployment
      labels:
        app: demo-voting-app
        name: result-app-deployment
    spec:
      containers:
        - name: result-app
          image: dockersamples/examplevotingapp_result
  replicas: 1
  selectors:
    matchLables:
      app: demo-voting-app
      name: result-app-deployment
