apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app-deployment
  labels:
    app: demo-voting-app
spec:
  template:
    metadata:
      name: worker-app-deployment
      labels:
        app: demo-voting-app
        name: worker-app-deployment
    spec:
      containers:
        - name: worker-app
          image: dockersamples/examplevotingapp_worker
  replicas: 1
  selector:
    matchLables:
      app: demo-voting-app
      name: worker-app-deployment
